### ISSUE TITLE
XCode 14.3 ADAL errors via Carthage

### ISSUE THREAD

**Issue by Bellu1980** [AzureAD/azure-activedirectory-library-for-objc#1600]
Hi there,

Since updating to XCode 14.3 from 14.2 Carthage will no longer build. here are some errors we are seeing.

```
/Users/username/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/azure-activedirectory-library-for-objc/117df96393342ac90447704529bf8c3366a61a6d/Build/Intermediates.noindex/ArchiveIntermediates/ADAL\ iOS/IntermediateBuildFilesPath/IdentityCore.build/Release-iphoneos/IdentityCore\ iOS.build/Objects-normal/arm64/MSIDError.o
/Users/username/Documents/Carthage/Checkouts/azure-activedirectory-library-for-objc/ADAL/IdentityCore/IdentityCore/src/MSIDError.m:84:39: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
NSDictionary* MSIDErrorDomainsAndCodes()
                                      ^
                                       void
1 error generated.
```

```
The following build commands failed:
	CompileC /Users/username/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/azure-activedirectory-library-for-objc/117df96393342ac90447704529bf8c3366a61a6d/Build/Intermediates.noindex/ArchiveIntermediates/ADAL\ iOS/IntermediateBuildFilesPath/IdentityCore.build/Release-iphoneos/IdentityCore\ iOS.build/Objects-normal/arm64/MSIDError.o /Users/username/Documents/Carthage/Checkouts/azure-activedirectory-library-for-objc/ADAL/IdentityCore/IdentityCore/src/MSIDError.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'IdentityCore iOS' from project 'IdentityCore')
(1 failure)
Build Failed
	Task failed with exit code 65:
```

Carthage: 0.39.0
XCode 14.3
macOS: Venture 13.3.1

Any help would be much appreciated.

**Comment by jasoncoolmax** [comment]
We do recommend you to update to use our latest auth library MSAL given that we are going to depreciate ADAL soon. Such an issue should not exist.

At the mean time, community help is greatly welcome to help solve the above Carthage issue ;)

**Comment by Bellu1980** [comment]
Thanks for the reply. Looks like the latest update to MSAL has it building with XCode 14.3. Will look into switching over to using that.
